### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by joyel24** [Vorschreibung/miss2-patches#3]
I have no dll error when opening in terminal but there is no help to know how to use it ?
What are the arguments needed ?
I'm trying to use it with to build this repo: https://github.com/Sergeanur/UndefinifiedLiberty

**Comment by Vorschreibung** [comment]
I think you've misread what this repository is about, you're probably looking for https://github.com/FunkyFr3sh/petool

**Comment by joyel24** [comment]
"automatically compile file passed from command line on startup and then exit"

Does it mean i just have to paste the file location next to miss.exe with a space ?

That was the question of the issue
